/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppExpedientesIndexRouteImport } from './routes/_app/expedientes/index'
import { Route as AppExpedientesExpedienteIdRouteImport } from './routes/_app/expedientes/$expedienteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedientesIndexRoute = AppExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedientesExpedienteIdRoute =
  AppExpedientesExpedienteIdRouteImport.update({
    id: '/expedientes/$expedienteId',
    path: '/expedientes/$expedienteId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRoute
  '/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/expedientes/': typeof AppExpedientesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRoute
  '/': typeof AppIndexRoute
  '/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/expedientes': typeof AppExpedientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/_app/expedientes/': typeof AppExpedientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/clientes'
    | '/expedientes/$expedienteId'
    | '/expedientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agenda'
    | '/clientes'
    | '/'
    | '/expedientes/$expedienteId'
    | '/expedientes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/clientes'
    | '/_app/'
    | '/_app/expedientes/$expedienteId'
    | '/_app/expedientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedientes/': {
      id: '/_app/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof AppExpedientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedientes/$expedienteId': {
      id: '/_app/expedientes/$expedienteId'
      path: '/expedientes/$expedienteId'
      fullPath: '/expedientes/$expedienteId'
      preLoaderRoute: typeof AppExpedientesExpedienteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExpedientesExpedienteIdRoute: typeof AppExpedientesExpedienteIdRoute
  AppExpedientesIndexRoute: typeof AppExpedientesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRoute,
  AppIndexRoute: AppIndexRoute,
  AppExpedientesExpedienteIdRoute: AppExpedientesExpedienteIdRoute,
  AppExpedientesIndexRoute: AppExpedientesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
