/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppExpedientesIndexRouteImport } from './routes/_app/expedientes/index'
import { Route as AppConfigIndexRouteImport } from './routes/_app/config/index'
import { Route as AppExpedientesExpedienteIdRouteImport } from './routes/_app/expedientes/$expedienteId'
import { Route as AppConfigTramitesIndexRouteImport } from './routes/_app/config/tramites/index'
import { Route as AppConfigServiciosIndexRouteImport } from './routes/_app/config/servicios/index'
import { Route as AppConfigTramitesNuevoRouteImport } from './routes/_app/config/tramites/nuevo'
import { Route as AppConfigTramitesTramiteIdRouteImport } from './routes/_app/config/tramites/$tramiteId'
import { Route as AppConfigServiciosNuevoRouteImport } from './routes/_app/config/servicios/nuevo'
import { Route as AppConfigServiciosServicioIdRouteImport } from './routes/_app/config/servicios/$servicioId'
import { Route as AppConfigTramitesTramiteIdIndexRouteImport } from './routes/_app/config/tramites/$tramiteId.index'
import { Route as AppConfigTramitesTramiteIdFasesRouteImport } from './routes/_app/config/tramites/$tramiteId.fases'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedientesIndexRoute = AppExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedientesExpedienteIdRoute =
  AppExpedientesExpedienteIdRouteImport.update({
    id: '/expedientes/$expedienteId',
    path: '/expedientes/$expedienteId',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfigTramitesIndexRoute = AppConfigTramitesIndexRouteImport.update({
  id: '/config/tramites/',
  path: '/config/tramites/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigServiciosIndexRoute = AppConfigServiciosIndexRouteImport.update({
  id: '/config/servicios/',
  path: '/config/servicios/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigTramitesNuevoRoute = AppConfigTramitesNuevoRouteImport.update({
  id: '/config/tramites/nuevo',
  path: '/config/tramites/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigTramitesTramiteIdRoute =
  AppConfigTramitesTramiteIdRouteImport.update({
    id: '/config/tramites/$tramiteId',
    path: '/config/tramites/$tramiteId',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfigServiciosNuevoRoute = AppConfigServiciosNuevoRouteImport.update({
  id: '/config/servicios/nuevo',
  path: '/config/servicios/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigServiciosServicioIdRoute =
  AppConfigServiciosServicioIdRouteImport.update({
    id: '/config/servicios/$servicioId',
    path: '/config/servicios/$servicioId',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfigTramitesTramiteIdIndexRoute =
  AppConfigTramitesTramiteIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppConfigTramitesTramiteIdRoute,
  } as any)
const AppConfigTramitesTramiteIdFasesRoute =
  AppConfigTramitesTramiteIdFasesRouteImport.update({
    id: '/fases',
    path: '/fases',
    getParentRoute: () => AppConfigTramitesTramiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/config/': typeof AppConfigIndexRoute
  '/expedientes/': typeof AppExpedientesIndexRoute
  '/config/servicios/$servicioId': typeof AppConfigServiciosServicioIdRoute
  '/config/servicios/nuevo': typeof AppConfigServiciosNuevoRoute
  '/config/tramites/$tramiteId': typeof AppConfigTramitesTramiteIdRouteWithChildren
  '/config/tramites/nuevo': typeof AppConfigTramitesNuevoRoute
  '/config/servicios/': typeof AppConfigServiciosIndexRoute
  '/config/tramites/': typeof AppConfigTramitesIndexRoute
  '/config/tramites/$tramiteId/fases': typeof AppConfigTramitesTramiteIdFasesRoute
  '/config/tramites/$tramiteId/': typeof AppConfigTramitesTramiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/': typeof AppIndexRoute
  '/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/config': typeof AppConfigIndexRoute
  '/expedientes': typeof AppExpedientesIndexRoute
  '/config/servicios/$servicioId': typeof AppConfigServiciosServicioIdRoute
  '/config/servicios/nuevo': typeof AppConfigServiciosNuevoRoute
  '/config/tramites/nuevo': typeof AppConfigTramitesNuevoRoute
  '/config/servicios': typeof AppConfigServiciosIndexRoute
  '/config/tramites': typeof AppConfigTramitesIndexRoute
  '/config/tramites/$tramiteId/fases': typeof AppConfigTramitesTramiteIdFasesRoute
  '/config/tramites/$tramiteId': typeof AppConfigTramitesTramiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/': typeof AppIndexRoute
  '/_app/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/_app/config/': typeof AppConfigIndexRoute
  '/_app/expedientes/': typeof AppExpedientesIndexRoute
  '/_app/config/servicios/$servicioId': typeof AppConfigServiciosServicioIdRoute
  '/_app/config/servicios/nuevo': typeof AppConfigServiciosNuevoRoute
  '/_app/config/tramites/$tramiteId': typeof AppConfigTramitesTramiteIdRouteWithChildren
  '/_app/config/tramites/nuevo': typeof AppConfigTramitesNuevoRoute
  '/_app/config/servicios/': typeof AppConfigServiciosIndexRoute
  '/_app/config/tramites/': typeof AppConfigTramitesIndexRoute
  '/_app/config/tramites/$tramiteId/fases': typeof AppConfigTramitesTramiteIdFasesRoute
  '/_app/config/tramites/$tramiteId/': typeof AppConfigTramitesTramiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/clientes'
    | '/dashboard'
    | '/expedientes/$expedienteId'
    | '/config/'
    | '/expedientes/'
    | '/config/servicios/$servicioId'
    | '/config/servicios/nuevo'
    | '/config/tramites/$tramiteId'
    | '/config/tramites/nuevo'
    | '/config/servicios/'
    | '/config/tramites/'
    | '/config/tramites/$tramiteId/fases'
    | '/config/tramites/$tramiteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agenda'
    | '/clientes'
    | '/dashboard'
    | '/'
    | '/expedientes/$expedienteId'
    | '/config'
    | '/expedientes'
    | '/config/servicios/$servicioId'
    | '/config/servicios/nuevo'
    | '/config/tramites/nuevo'
    | '/config/servicios'
    | '/config/tramites'
    | '/config/tramites/$tramiteId/fases'
    | '/config/tramites/$tramiteId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/clientes'
    | '/_app/dashboard'
    | '/_app/'
    | '/_app/expedientes/$expedienteId'
    | '/_app/config/'
    | '/_app/expedientes/'
    | '/_app/config/servicios/$servicioId'
    | '/_app/config/servicios/nuevo'
    | '/_app/config/tramites/$tramiteId'
    | '/_app/config/tramites/nuevo'
    | '/_app/config/servicios/'
    | '/_app/config/tramites/'
    | '/_app/config/tramites/$tramiteId/fases'
    | '/_app/config/tramites/$tramiteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedientes/': {
      id: '/_app/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof AppExpedientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/': {
      id: '/_app/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedientes/$expedienteId': {
      id: '/_app/expedientes/$expedienteId'
      path: '/expedientes/$expedienteId'
      fullPath: '/expedientes/$expedienteId'
      preLoaderRoute: typeof AppExpedientesExpedienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/tramites/': {
      id: '/_app/config/tramites/'
      path: '/config/tramites'
      fullPath: '/config/tramites/'
      preLoaderRoute: typeof AppConfigTramitesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/servicios/': {
      id: '/_app/config/servicios/'
      path: '/config/servicios'
      fullPath: '/config/servicios/'
      preLoaderRoute: typeof AppConfigServiciosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/tramites/nuevo': {
      id: '/_app/config/tramites/nuevo'
      path: '/config/tramites/nuevo'
      fullPath: '/config/tramites/nuevo'
      preLoaderRoute: typeof AppConfigTramitesNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/tramites/$tramiteId': {
      id: '/_app/config/tramites/$tramiteId'
      path: '/config/tramites/$tramiteId'
      fullPath: '/config/tramites/$tramiteId'
      preLoaderRoute: typeof AppConfigTramitesTramiteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/servicios/nuevo': {
      id: '/_app/config/servicios/nuevo'
      path: '/config/servicios/nuevo'
      fullPath: '/config/servicios/nuevo'
      preLoaderRoute: typeof AppConfigServiciosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/servicios/$servicioId': {
      id: '/_app/config/servicios/$servicioId'
      path: '/config/servicios/$servicioId'
      fullPath: '/config/servicios/$servicioId'
      preLoaderRoute: typeof AppConfigServiciosServicioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/tramites/$tramiteId/': {
      id: '/_app/config/tramites/$tramiteId/'
      path: '/'
      fullPath: '/config/tramites/$tramiteId/'
      preLoaderRoute: typeof AppConfigTramitesTramiteIdIndexRouteImport
      parentRoute: typeof AppConfigTramitesTramiteIdRoute
    }
    '/_app/config/tramites/$tramiteId/fases': {
      id: '/_app/config/tramites/$tramiteId/fases'
      path: '/fases'
      fullPath: '/config/tramites/$tramiteId/fases'
      preLoaderRoute: typeof AppConfigTramitesTramiteIdFasesRouteImport
      parentRoute: typeof AppConfigTramitesTramiteIdRoute
    }
  }
}

interface AppConfigTramitesTramiteIdRouteChildren {
  AppConfigTramitesTramiteIdFasesRoute: typeof AppConfigTramitesTramiteIdFasesRoute
  AppConfigTramitesTramiteIdIndexRoute: typeof AppConfigTramitesTramiteIdIndexRoute
}

const AppConfigTramitesTramiteIdRouteChildren: AppConfigTramitesTramiteIdRouteChildren =
  {
    AppConfigTramitesTramiteIdFasesRoute: AppConfigTramitesTramiteIdFasesRoute,
    AppConfigTramitesTramiteIdIndexRoute: AppConfigTramitesTramiteIdIndexRoute,
  }

const AppConfigTramitesTramiteIdRouteWithChildren =
  AppConfigTramitesTramiteIdRoute._addFileChildren(
    AppConfigTramitesTramiteIdRouteChildren,
  )

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExpedientesExpedienteIdRoute: typeof AppExpedientesExpedienteIdRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
  AppExpedientesIndexRoute: typeof AppExpedientesIndexRoute
  AppConfigServiciosServicioIdRoute: typeof AppConfigServiciosServicioIdRoute
  AppConfigServiciosNuevoRoute: typeof AppConfigServiciosNuevoRoute
  AppConfigTramitesTramiteIdRoute: typeof AppConfigTramitesTramiteIdRouteWithChildren
  AppConfigTramitesNuevoRoute: typeof AppConfigTramitesNuevoRoute
  AppConfigServiciosIndexRoute: typeof AppConfigServiciosIndexRoute
  AppConfigTramitesIndexRoute: typeof AppConfigTramitesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppExpedientesExpedienteIdRoute: AppExpedientesExpedienteIdRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
  AppExpedientesIndexRoute: AppExpedientesIndexRoute,
  AppConfigServiciosServicioIdRoute: AppConfigServiciosServicioIdRoute,
  AppConfigServiciosNuevoRoute: AppConfigServiciosNuevoRoute,
  AppConfigTramitesTramiteIdRoute: AppConfigTramitesTramiteIdRouteWithChildren,
  AppConfigTramitesNuevoRoute: AppConfigTramitesNuevoRoute,
  AppConfigServiciosIndexRoute: AppConfigServiciosIndexRoute,
  AppConfigTramitesIndexRoute: AppConfigTramitesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
