/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentCancelRouteImport } from './routes/payment/cancel'
import { Route as AccesoTokenRouteImport } from './routes/acceso/$token'
import { Route as AppFacturacionRouteImport } from './routes/_app/facturacion'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppExpedientesIndexRouteImport } from './routes/_app/expedientes/index'
import { Route as AppConfigIndexRouteImport } from './routes/_app/config/index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes/index'
import { Route as AppExpedientesNuevoRouteImport } from './routes/_app/expedientes/nuevo'
import { Route as AppExpedientesExpedienteIdRouteImport } from './routes/_app/expedientes/$expedienteId'
import { Route as AppConfigDespachoRouteImport } from './routes/_app/config/despacho'
import { Route as AppClientesNuevoRouteImport } from './routes/_app/clientes/nuevo'
import { Route as AppClientesClienteIdRouteImport } from './routes/_app/clientes/$clienteId'
import { Route as AppConfigTramitesIndexRouteImport } from './routes/_app/config/tramites/index'
import { Route as AppConfigServiciosIndexRouteImport } from './routes/_app/config/servicios/index'
import { Route as AppConfigTramitesNuevoRouteImport } from './routes/_app/config/tramites/nuevo'
import { Route as AppConfigTramitesTramiteIdRouteImport } from './routes/_app/config/tramites/$tramiteId'
import { Route as AppConfigServiciosNuevoRouteImport } from './routes/_app/config/servicios/nuevo'
import { Route as AppConfigServiciosServicioIdRouteImport } from './routes/_app/config/servicios/$servicioId'
import { Route as AppConfigTramitesTramiteIdIndexRouteImport } from './routes/_app/config/tramites/$tramiteId.index'
import { Route as AppConfigTramitesTramiteIdHojaEncargoRouteImport } from './routes/_app/config/tramites/$tramiteId.hoja-encargo'
import { Route as AppConfigTramitesTramiteIdFasesRouteImport } from './routes/_app/config/tramites/$tramiteId.fases'
import { Route as AppConfigTramitesTramiteIdConfiguracionRouteImport } from './routes/_app/config/tramites/$tramiteId.configuracion'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoTokenRoute = AccesoTokenRouteImport.update({
  id: '/acceso/$token',
  path: '/acceso/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFacturacionRoute = AppFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedientesIndexRoute = AppExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedientesNuevoRoute = AppExpedientesNuevoRouteImport.update({
  id: '/expedientes/nuevo',
  path: '/expedientes/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedientesExpedienteIdRoute =
  AppExpedientesExpedienteIdRouteImport.update({
    id: '/expedientes/$expedienteId',
    path: '/expedientes/$expedienteId',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfigDespachoRoute = AppConfigDespachoRouteImport.update({
  id: '/config/despacho',
  path: '/config/despacho',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesNuevoRoute = AppClientesNuevoRouteImport.update({
  id: '/clientes/nuevo',
  path: '/clientes/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigTramitesIndexRoute = AppConfigTramitesIndexRouteImport.update({
  id: '/config/tramites/',
  path: '/config/tramites/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigServiciosIndexRoute = AppConfigServiciosIndexRouteImport.update({
  id: '/config/servicios/',
  path: '/config/servicios/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigTramitesNuevoRoute = AppConfigTramitesNuevoRouteImport.update({
  id: '/config/tramites/nuevo',
  path: '/config/tramites/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigTramitesTramiteIdRoute =
  AppConfigTramitesTramiteIdRouteImport.update({
    id: '/config/tramites/$tramiteId',
    path: '/config/tramites/$tramiteId',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfigServiciosNuevoRoute = AppConfigServiciosNuevoRouteImport.update({
  id: '/config/servicios/nuevo',
  path: '/config/servicios/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigServiciosServicioIdRoute =
  AppConfigServiciosServicioIdRouteImport.update({
    id: '/config/servicios/$servicioId',
    path: '/config/servicios/$servicioId',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfigTramitesTramiteIdIndexRoute =
  AppConfigTramitesTramiteIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppConfigTramitesTramiteIdRoute,
  } as any)
const AppConfigTramitesTramiteIdHojaEncargoRoute =
  AppConfigTramitesTramiteIdHojaEncargoRouteImport.update({
    id: '/hoja-encargo',
    path: '/hoja-encargo',
    getParentRoute: () => AppConfigTramitesTramiteIdRoute,
  } as any)
const AppConfigTramitesTramiteIdFasesRoute =
  AppConfigTramitesTramiteIdFasesRouteImport.update({
    id: '/fases',
    path: '/fases',
    getParentRoute: () => AppConfigTramitesTramiteIdRoute,
  } as any)
const AppConfigTramitesTramiteIdConfiguracionRoute =
  AppConfigTramitesTramiteIdConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AppConfigTramitesTramiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/dashboard': typeof AppDashboardRoute
  '/facturacion': typeof AppFacturacionRoute
  '/acceso/$token': typeof AccesoTokenRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/config/despacho': typeof AppConfigDespachoRoute
  '/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/expedientes/nuevo': typeof AppExpedientesNuevoRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/config/': typeof AppConfigIndexRoute
  '/expedientes/': typeof AppExpedientesIndexRoute
  '/config/servicios/$servicioId': typeof AppConfigServiciosServicioIdRoute
  '/config/servicios/nuevo': typeof AppConfigServiciosNuevoRoute
  '/config/tramites/$tramiteId': typeof AppConfigTramitesTramiteIdRouteWithChildren
  '/config/tramites/nuevo': typeof AppConfigTramitesNuevoRoute
  '/config/servicios/': typeof AppConfigServiciosIndexRoute
  '/config/tramites/': typeof AppConfigTramitesIndexRoute
  '/config/tramites/$tramiteId/configuracion': typeof AppConfigTramitesTramiteIdConfiguracionRoute
  '/config/tramites/$tramiteId/fases': typeof AppConfigTramitesTramiteIdFasesRoute
  '/config/tramites/$tramiteId/hoja-encargo': typeof AppConfigTramitesTramiteIdHojaEncargoRoute
  '/config/tramites/$tramiteId/': typeof AppConfigTramitesTramiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/dashboard': typeof AppDashboardRoute
  '/facturacion': typeof AppFacturacionRoute
  '/acceso/$token': typeof AccesoTokenRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/': typeof AppIndexRoute
  '/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/config/despacho': typeof AppConfigDespachoRoute
  '/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/expedientes/nuevo': typeof AppExpedientesNuevoRoute
  '/clientes': typeof AppClientesIndexRoute
  '/config': typeof AppConfigIndexRoute
  '/expedientes': typeof AppExpedientesIndexRoute
  '/config/servicios/$servicioId': typeof AppConfigServiciosServicioIdRoute
  '/config/servicios/nuevo': typeof AppConfigServiciosNuevoRoute
  '/config/tramites/nuevo': typeof AppConfigTramitesNuevoRoute
  '/config/servicios': typeof AppConfigServiciosIndexRoute
  '/config/tramites': typeof AppConfigTramitesIndexRoute
  '/config/tramites/$tramiteId/configuracion': typeof AppConfigTramitesTramiteIdConfiguracionRoute
  '/config/tramites/$tramiteId/fases': typeof AppConfigTramitesTramiteIdFasesRoute
  '/config/tramites/$tramiteId/hoja-encargo': typeof AppConfigTramitesTramiteIdHojaEncargoRoute
  '/config/tramites/$tramiteId': typeof AppConfigTramitesTramiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/facturacion': typeof AppFacturacionRoute
  '/acceso/$token': typeof AccesoTokenRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/_app/clientes/nuevo': typeof AppClientesNuevoRoute
  '/_app/config/despacho': typeof AppConfigDespachoRoute
  '/_app/expedientes/$expedienteId': typeof AppExpedientesExpedienteIdRoute
  '/_app/expedientes/nuevo': typeof AppExpedientesNuevoRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/config/': typeof AppConfigIndexRoute
  '/_app/expedientes/': typeof AppExpedientesIndexRoute
  '/_app/config/servicios/$servicioId': typeof AppConfigServiciosServicioIdRoute
  '/_app/config/servicios/nuevo': typeof AppConfigServiciosNuevoRoute
  '/_app/config/tramites/$tramiteId': typeof AppConfigTramitesTramiteIdRouteWithChildren
  '/_app/config/tramites/nuevo': typeof AppConfigTramitesNuevoRoute
  '/_app/config/servicios/': typeof AppConfigServiciosIndexRoute
  '/_app/config/tramites/': typeof AppConfigTramitesIndexRoute
  '/_app/config/tramites/$tramiteId/configuracion': typeof AppConfigTramitesTramiteIdConfiguracionRoute
  '/_app/config/tramites/$tramiteId/fases': typeof AppConfigTramitesTramiteIdFasesRoute
  '/_app/config/tramites/$tramiteId/hoja-encargo': typeof AppConfigTramitesTramiteIdHojaEncargoRoute
  '/_app/config/tramites/$tramiteId/': typeof AppConfigTramitesTramiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/dashboard'
    | '/facturacion'
    | '/acceso/$token'
    | '/payment/cancel'
    | '/payment/success'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/config/despacho'
    | '/expedientes/$expedienteId'
    | '/expedientes/nuevo'
    | '/clientes/'
    | '/config/'
    | '/expedientes/'
    | '/config/servicios/$servicioId'
    | '/config/servicios/nuevo'
    | '/config/tramites/$tramiteId'
    | '/config/tramites/nuevo'
    | '/config/servicios/'
    | '/config/tramites/'
    | '/config/tramites/$tramiteId/configuracion'
    | '/config/tramites/$tramiteId/fases'
    | '/config/tramites/$tramiteId/hoja-encargo'
    | '/config/tramites/$tramiteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agenda'
    | '/dashboard'
    | '/facturacion'
    | '/acceso/$token'
    | '/payment/cancel'
    | '/payment/success'
    | '/'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/config/despacho'
    | '/expedientes/$expedienteId'
    | '/expedientes/nuevo'
    | '/clientes'
    | '/config'
    | '/expedientes'
    | '/config/servicios/$servicioId'
    | '/config/servicios/nuevo'
    | '/config/tramites/nuevo'
    | '/config/servicios'
    | '/config/tramites'
    | '/config/tramites/$tramiteId/configuracion'
    | '/config/tramites/$tramiteId/fases'
    | '/config/tramites/$tramiteId/hoja-encargo'
    | '/config/tramites/$tramiteId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/dashboard'
    | '/_app/facturacion'
    | '/acceso/$token'
    | '/payment/cancel'
    | '/payment/success'
    | '/_app/'
    | '/_app/clientes/$clienteId'
    | '/_app/clientes/nuevo'
    | '/_app/config/despacho'
    | '/_app/expedientes/$expedienteId'
    | '/_app/expedientes/nuevo'
    | '/_app/clientes/'
    | '/_app/config/'
    | '/_app/expedientes/'
    | '/_app/config/servicios/$servicioId'
    | '/_app/config/servicios/nuevo'
    | '/_app/config/tramites/$tramiteId'
    | '/_app/config/tramites/nuevo'
    | '/_app/config/servicios/'
    | '/_app/config/tramites/'
    | '/_app/config/tramites/$tramiteId/configuracion'
    | '/_app/config/tramites/$tramiteId/fases'
    | '/_app/config/tramites/$tramiteId/hoja-encargo'
    | '/_app/config/tramites/$tramiteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AccesoTokenRoute: typeof AccesoTokenRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso/$token': {
      id: '/acceso/$token'
      path: '/acceso/$token'
      fullPath: '/acceso/$token'
      preLoaderRoute: typeof AccesoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/facturacion': {
      id: '/_app/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AppFacturacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedientes/': {
      id: '/_app/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof AppExpedientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/': {
      id: '/_app/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedientes/nuevo': {
      id: '/_app/expedientes/nuevo'
      path: '/expedientes/nuevo'
      fullPath: '/expedientes/nuevo'
      preLoaderRoute: typeof AppExpedientesNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedientes/$expedienteId': {
      id: '/_app/expedientes/$expedienteId'
      path: '/expedientes/$expedienteId'
      fullPath: '/expedientes/$expedienteId'
      preLoaderRoute: typeof AppExpedientesExpedienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/despacho': {
      id: '/_app/config/despacho'
      path: '/config/despacho'
      fullPath: '/config/despacho'
      preLoaderRoute: typeof AppConfigDespachoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/nuevo': {
      id: '/_app/clientes/nuevo'
      path: '/clientes/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof AppClientesNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$clienteId': {
      id: '/_app/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/tramites/': {
      id: '/_app/config/tramites/'
      path: '/config/tramites'
      fullPath: '/config/tramites/'
      preLoaderRoute: typeof AppConfigTramitesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/servicios/': {
      id: '/_app/config/servicios/'
      path: '/config/servicios'
      fullPath: '/config/servicios/'
      preLoaderRoute: typeof AppConfigServiciosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/tramites/nuevo': {
      id: '/_app/config/tramites/nuevo'
      path: '/config/tramites/nuevo'
      fullPath: '/config/tramites/nuevo'
      preLoaderRoute: typeof AppConfigTramitesNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/tramites/$tramiteId': {
      id: '/_app/config/tramites/$tramiteId'
      path: '/config/tramites/$tramiteId'
      fullPath: '/config/tramites/$tramiteId'
      preLoaderRoute: typeof AppConfigTramitesTramiteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/servicios/nuevo': {
      id: '/_app/config/servicios/nuevo'
      path: '/config/servicios/nuevo'
      fullPath: '/config/servicios/nuevo'
      preLoaderRoute: typeof AppConfigServiciosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/servicios/$servicioId': {
      id: '/_app/config/servicios/$servicioId'
      path: '/config/servicios/$servicioId'
      fullPath: '/config/servicios/$servicioId'
      preLoaderRoute: typeof AppConfigServiciosServicioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/tramites/$tramiteId/': {
      id: '/_app/config/tramites/$tramiteId/'
      path: '/'
      fullPath: '/config/tramites/$tramiteId/'
      preLoaderRoute: typeof AppConfigTramitesTramiteIdIndexRouteImport
      parentRoute: typeof AppConfigTramitesTramiteIdRoute
    }
    '/_app/config/tramites/$tramiteId/hoja-encargo': {
      id: '/_app/config/tramites/$tramiteId/hoja-encargo'
      path: '/hoja-encargo'
      fullPath: '/config/tramites/$tramiteId/hoja-encargo'
      preLoaderRoute: typeof AppConfigTramitesTramiteIdHojaEncargoRouteImport
      parentRoute: typeof AppConfigTramitesTramiteIdRoute
    }
    '/_app/config/tramites/$tramiteId/fases': {
      id: '/_app/config/tramites/$tramiteId/fases'
      path: '/fases'
      fullPath: '/config/tramites/$tramiteId/fases'
      preLoaderRoute: typeof AppConfigTramitesTramiteIdFasesRouteImport
      parentRoute: typeof AppConfigTramitesTramiteIdRoute
    }
    '/_app/config/tramites/$tramiteId/configuracion': {
      id: '/_app/config/tramites/$tramiteId/configuracion'
      path: '/configuracion'
      fullPath: '/config/tramites/$tramiteId/configuracion'
      preLoaderRoute: typeof AppConfigTramitesTramiteIdConfiguracionRouteImport
      parentRoute: typeof AppConfigTramitesTramiteIdRoute
    }
  }
}

interface AppConfigTramitesTramiteIdRouteChildren {
  AppConfigTramitesTramiteIdConfiguracionRoute: typeof AppConfigTramitesTramiteIdConfiguracionRoute
  AppConfigTramitesTramiteIdFasesRoute: typeof AppConfigTramitesTramiteIdFasesRoute
  AppConfigTramitesTramiteIdHojaEncargoRoute: typeof AppConfigTramitesTramiteIdHojaEncargoRoute
  AppConfigTramitesTramiteIdIndexRoute: typeof AppConfigTramitesTramiteIdIndexRoute
}

const AppConfigTramitesTramiteIdRouteChildren: AppConfigTramitesTramiteIdRouteChildren =
  {
    AppConfigTramitesTramiteIdConfiguracionRoute:
      AppConfigTramitesTramiteIdConfiguracionRoute,
    AppConfigTramitesTramiteIdFasesRoute: AppConfigTramitesTramiteIdFasesRoute,
    AppConfigTramitesTramiteIdHojaEncargoRoute:
      AppConfigTramitesTramiteIdHojaEncargoRoute,
    AppConfigTramitesTramiteIdIndexRoute: AppConfigTramitesTramiteIdIndexRoute,
  }

const AppConfigTramitesTramiteIdRouteWithChildren =
  AppConfigTramitesTramiteIdRoute._addFileChildren(
    AppConfigTramitesTramiteIdRouteChildren,
  )

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFacturacionRoute: typeof AppFacturacionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRoute
  AppClientesNuevoRoute: typeof AppClientesNuevoRoute
  AppConfigDespachoRoute: typeof AppConfigDespachoRoute
  AppExpedientesExpedienteIdRoute: typeof AppExpedientesExpedienteIdRoute
  AppExpedientesNuevoRoute: typeof AppExpedientesNuevoRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
  AppExpedientesIndexRoute: typeof AppExpedientesIndexRoute
  AppConfigServiciosServicioIdRoute: typeof AppConfigServiciosServicioIdRoute
  AppConfigServiciosNuevoRoute: typeof AppConfigServiciosNuevoRoute
  AppConfigTramitesTramiteIdRoute: typeof AppConfigTramitesTramiteIdRouteWithChildren
  AppConfigTramitesNuevoRoute: typeof AppConfigTramitesNuevoRoute
  AppConfigServiciosIndexRoute: typeof AppConfigServiciosIndexRoute
  AppConfigTramitesIndexRoute: typeof AppConfigTramitesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFacturacionRoute: AppFacturacionRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesClienteIdRoute: AppClientesClienteIdRoute,
  AppClientesNuevoRoute: AppClientesNuevoRoute,
  AppConfigDespachoRoute: AppConfigDespachoRoute,
  AppExpedientesExpedienteIdRoute: AppExpedientesExpedienteIdRoute,
  AppExpedientesNuevoRoute: AppExpedientesNuevoRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
  AppExpedientesIndexRoute: AppExpedientesIndexRoute,
  AppConfigServiciosServicioIdRoute: AppConfigServiciosServicioIdRoute,
  AppConfigServiciosNuevoRoute: AppConfigServiciosNuevoRoute,
  AppConfigTramitesTramiteIdRoute: AppConfigTramitesTramiteIdRouteWithChildren,
  AppConfigTramitesNuevoRoute: AppConfigTramitesNuevoRoute,
  AppConfigServiciosIndexRoute: AppConfigServiciosIndexRoute,
  AppConfigTramitesIndexRoute: AppConfigTramitesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AccesoTokenRoute: AccesoTokenRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
