<?php

declare(strict_types=1);

namespace App\Infrastructure\Persistence\Migration;

/**
 * Catálogo de nacionalidades (ISO 3166-1 alpha-3 → demónimo en español).
 *
 * @phpstan-type NacionalidadSeed array{codigo: string, nombre: string}
 */
final class NacionalidadSeedData
{
    /**
     * @return list<NacionalidadSeed>
     */
    public static function all(): array
    {
        $items = [];
        foreach (self::mapa() as $codigo => $nombre) {
            $items[] = ['codigo' => $codigo, 'nombre' => $nombre];
        }

        return $items;
    }

    public static function nombrePorCodigo(string $codigo): ?string
    {
        $codigo = strtoupper(trim($codigo));

        return self::mapa()[$codigo] ?? null;
    }

    /**
     * @return array<string, string>
     */
    public static function mapa(): array
    {
        return [
            'AFG' => 'Afgana',
            'ALB' => 'Albanesa',
            'DZA' => 'Argelina',
            'AND' => 'Andorrana',
            'AGO' => 'Angoleña',
            'ARG' => 'Argentina',
            'ARM' => 'Armenia',
            'AUS' => 'Australiana',
            'AUT' => 'Austriaca',
            'AZE' => 'Azerbaiyana',
            'BHS' => 'Bahameña',
            'BHR' => 'Bahreiní',
            'BGD' => 'Bangladesí',
            'BRB' => 'Barbadense',
            'BLR' => 'Bielorrusa',
            'BEL' => 'Belga',
            'BLZ' => 'Beliceña',
            'BEN' => 'Beninesa',
            'BTN' => 'Butanesa',
            'BOL' => 'Boliviana',
            'BIH' => 'Bosnia',
            'BWA' => 'Botsuana',
            'BRA' => 'Brasileña',
            'BRN' => 'Bruneana',
            'BGR' => 'Búlgara',
            'BFA' => 'Burkinesa',
            'BDI' => 'Burundesa',
            'CPV' => 'Caboverdiana',
            'KHM' => 'Camboyana',
            'CMR' => 'Camerunesa',
            'CAN' => 'Canadiense',
            'CAF' => 'Centroafricana',
            'TCD' => 'Chadiana',
            'CHL' => 'Chilena',
            'CHN' => 'China',
            'COL' => 'Colombiana',
            'COM' => 'Comorense',
            'COG' => 'Congoleña',
            'COD' => 'Congoleña (RDC)',
            'CRI' => 'Costarricense',
            'CIV' => 'Marfileña',
            'HRV' => 'Croata',
            'CUB' => 'Cubana',
            'CYP' => 'Chipriota',
            'CZE' => 'Checa',
            'DNK' => 'Danesa',
            'DJI' => 'Yibutiana',
            'DOM' => 'Dominicana',
            'ECU' => 'Ecuatoriana',
            'EGY' => 'Egipcia',
            'SLV' => 'Salvadoreña',
            'GNQ' => 'Ecuatoguineana',
            'ERI' => 'Eritrea',
            'EST' => 'Estonia',
            'SWZ' => 'Suazi',
            'ETH' => 'Etíope',
            'FJI' => 'Fiyiana',
            'FIN' => 'Finlandesa',
            'FRA' => 'Francesa',
            'GAB' => 'Gabonesa',
            'GMB' => 'Gambiana',
            'GEO' => 'Georgiana',
            'DEU' => 'Alemana',
            'GHA' => 'Ghanesa',
            'GRC' => 'Griega',
            'GTM' => 'Guatemalteca',
            'GIN' => 'Guineana',
            'GNB' => 'Guineana-Bisáu',
            'GUY' => 'Guyanesa',
            'HTI' => 'Haitiana',
            'HND' => 'Hondureña',
            'HUN' => 'Húngara',
            'ISL' => 'Islandesa',
            'IND' => 'India',
            'IDN' => 'Indonesia',
            'IRN' => 'Iraní',
            'IRQ' => 'Iraquí',
            'IRL' => 'Irlandesa',
            'ISR' => 'Israelí',
            'ITA' => 'Italiana',
            'JAM' => 'Jamaicana',
            'JPN' => 'Japonesa',
            'JOR' => 'Jordana',
            'KAZ' => 'Kazaja',
            'KEN' => 'Keniana',
            'XKX' => 'Kosovar',
            'KWT' => 'Kuwaití',
            'KGZ' => 'Kirguisa',
            'LAO' => 'Laosiana',
            'LVA' => 'Letona',
            'LBN' => 'Libanesa',
            'LBR' => 'Liberiana',
            'LBY' => 'Libia',
            'LIE' => 'Liechtensteiniana',
            'LTU' => 'Lituana',
            'LUX' => 'Luxemburguesa',
            'MDG' => 'Malgache',
            'MWI' => 'Malauí',
            'MYS' => 'Malasia',
            'MDV' => 'Maldiva',
            'MLI' => 'Maliense',
            'MLT' => 'Maltesa',
            'MRT' => 'Mauritana',
            'MUS' => 'Mauriciana',
            'MEX' => 'Mexicana',
            'MDA' => 'Moldava',
            'MCO' => 'Monegasca',
            'MNG' => 'Mongola',
            'MNE' => 'Montenegrina',
            'MAR' => 'Marroquí',
            'MOZ' => 'Mozambiqueña',
            'MMR' => 'Birmana',
            'NAM' => 'Namibia',
            'NPL' => 'Nepalí',
            'NLD' => 'Neerlandesa',
            'NZL' => 'Neozelandesa',
            'NIC' => 'Nicaragüense',
            'NER' => 'Nigerina',
            'NGA' => 'Nigeriana',
            'PRK' => 'Norcoreana',
            'MKD' => 'Macedonia del Norte',
            'NOR' => 'Noruega',
            'OMN' => 'Omaní',
            'PAK' => 'Pakistaní',
            'PSE' => 'Palestina',
            'PAN' => 'Panameña',
            'PNG' => 'Papú',
            'PRY' => 'Paraguaya',
            'PER' => 'Peruana',
            'PHL' => 'Filipina',
            'POL' => 'Polaca',
            'PRT' => 'Portuguesa',
            'QAT' => 'Catarí',
            'ROU' => 'Rumana',
            'RUS' => 'Rusa',
            'RWA' => 'Ruandesa',
            'KNA' => 'Sancristobaleña',
            'LCA' => 'Santalucense',
            'VCT' => 'Sanvicentina',
            'WSM' => 'Samoana',
            'SMR' => 'Sanmarinense',
            'STP' => 'Santotomense',
            'SAU' => 'Saudí',
            'SEN' => 'Senegalesa',
            'SRB' => 'Serbia',
            'SYC' => 'Seychellense',
            'SLE' => 'Sierraleonesa',
            'SGP' => 'Singapurense',
            'SVK' => 'Eslovaca',
            'SVN' => 'Eslovena',
            'SOM' => 'Somalí',
            'ZAF' => 'Sudafricana',
            'KOR' => 'Surcoreana',
            'SSD' => 'SurSudanesa',
            'ESP' => 'Española',
            'LKA' => 'Ceilandesa',
            'SDN' => 'Sudanesa',
            'SUR' => 'Surinamesa',
            'SWE' => 'Sueca',
            'CHE' => 'Suiza',
            'SYR' => 'Siria',
            'TWN' => 'Taiwanesa',
            'TJK' => 'Tayika',
            'TZA' => 'Tanzana',
            'THA' => 'Tailandesa',
            'TLS' => 'Timorense',
            'TGO' => 'Togolesa',
            'TTO' => 'Trinitense',
            'TUN' => 'Tunecina',
            'TUR' => 'Turca',
            'TKM' => 'Turcomana',
            'UGA' => 'Ugandesa',
            'UKR' => 'Ucraniana',
            'ARE' => 'Emiratí',
            'GBR' => 'Británica',
            'USA' => 'Estadounidense',
            'URY' => 'Uruguaya',
            'UZB' => 'Uzbeka',
            'VEN' => 'Venezolana',
            'VNM' => 'Vietnamita',
            'YEM' => 'Yemení',
            'ZMB' => 'Zambiana',
            'ZWE' => 'Zimbabuense',
        ];
    }
}
